[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OperationsResearchModels = "8042aa49-e599-49ec-a8f7-b5b80cc82a88"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
